/**
 * Emits src/entrypoints/sdk/coreTypes.generated.ts from lazy Zod schemas in coreSchemas.ts.
 * Run: bun scripts/generate-sdk-types.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const coreSchemasPath = join(root, 'src/entrypoints/sdk/coreSchemas.ts')
const outPath = join(root, 'src/entrypoints/sdk/coreTypes.generated.ts')

const src = readFileSync(coreSchemasPath, 'utf8')
const re = /^export const (\w+Schema) = lazySchema/gm
const names: string[] = []
let m: RegExpExecArray | null
while ((m = re.exec(src)) !== null) {
  names.push(m[1])
}

const lines = [
  '// Generated by scripts/generate-sdk-types.ts — do not edit by hand',
  "import type { z } from 'zod/v4'",
  "import * as S from './coreSchemas.js'",
  '',
  'type InferLazy<T extends () => z.ZodType> = z.infer<ReturnType<T>>',
  '',
]

for (const schemaName of names) {
  const typeName = schemaName.replace(/Schema$/, '')
  lines.push(`export type ${typeName} = InferLazy<typeof S.${schemaName}>`)
}

writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8')
console.log(`Wrote ${names.length} types to coreTypes.generated.ts`)
